# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         reslog
version:      3.04
version_from: reslog
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
